### ISSUE TITLE
feat: 支持typescript

### ISSUE THREAD

**Issue by aladdin-add** [raxjs/rax-scripts#3]

**Comment by Orange-C** [comment]
工程方面是支持的，只是文档和模版没有透出，请问有什么具体的问题吗？

**Comment by aladdin-add** [comment]
背景是这样的：
1. 我在官方的模板的基础上增加了 typescript相关的配置
2. 新建应用
![image](https://user-images.githubusercontent.com/13050025/64396551-8ebb0500-d090-11e9-8de6-e74020bb1ef2.png)

3. npm run build, 会报错(如果选择组件是正常的）
<detail>

```bash
    ERROR in ./src/app.js (multi ./node_modules/rax-plugin-app/src/loaders/UniversalAppShellLoader?type=web!./src/app.js)
    Module not found: Error: Can't resolve '/Users/weiran/repo/gitlab/rax-app/src/app.js' in '/Users/weiran/repo/gitlab/rax-app'
     @ ./src/app.js (multi ./node_modules/rax-plugin-app/src/loaders/UniversalAppShellLoader?type=web!./src/app.js) index[0]
Child
    Hash: ba2db30bcf829491b304
    Time: 2369ms
    Built at: 2019-09-06 10:18:17 AM
                             Asset      Size  Chunks  Chunk Names
        server/pages_Home_index.js  3.64 KiB       0  pages_Home_index
    server/pages_Home_index.js.map  4.54 KiB       0  pages_Home_index
    
    ERROR in ./src/pages/Home/index.ts (./node_modules/rax-plugin-ssr/src/ssr/loader.js?path=%2F&pageName=pages_Home_index&absoluteDocumentPath=%2FUsers%2Fweiran%2Frepo%2Fgitlab%2Frax-app%2Fsrc%2Fdocument%2Findex.jsx&absoluteShellPath=%2FUsers%2Fweiran%2Frepo%2Fgitlab%2Frax-app%2Fsrc%2Fshell%2Findex.jsx&absoluteAppPath=%2FUsers%2Fweiran%2Frepo%2Fgitlab%2Frax-app%2Fsrc%2Fapp.js&absolutePagePath=%2FUsers%2Fweiran%2Frepo%2Fgitlab%2Frax-app%2Fsrc%2Fpages%2FHome%2Findex&absoluteAppJSONPath=%2FUsers%2Fweiran%2Frepo%2Fgitlab%2Frax-app%2Fsrc%2Fapp.json&publicPath=%2F&isMultiPages=false&scripts%5B0%5D=web%2Fpages_Home_index.js&scripts%5B1%5D=web%2Findex.js!./src/pages/Home/index.ts)
    Module build failed (from ./node_modules/babel-loader/lib/index.js):
    SyntaxError: /Users/weiran/repo/gitlab/rax-app/src/pages/Home/index.ts: Unexpected token (4:29)
    
      2 | import styles from './index.css';
      3 | export default function Home() {
    > 4 |     return style = { styles, : .home } >
        |                              ^
      5 |         />
      6 |         < Text;
      7 |     style = { styles, : .title } > Welcome;
        at Object.raise (/Users/weiran/repo/gitlab/rax-app/node_modules/@babel/parser/lib/index.js:6325:17)
        at Object.unexpected (/Users/weiran/repo/gitlab/rax-app/node_modules/@babel/parser/lib/index.js:7642:16)
        at Object.parseIdentifierName (/Users/weiran/repo/gitlab/rax-app/node_modules/@babel/parser/lib/index.js:9521:18)
        at Object.parseIdentifier (/Users/weiran/repo/gitlab/rax-app/node_modules/@babel/parser/lib/index.js:9499:23)
        at Object.parseMaybePrivateName (/Users/weiran/repo/gitlab/rax-app/node_modules/@babel/parser/lib/index.js:8863:19)
        at Object.parsePropertyName (/Users/weiran/repo/gitlab/rax-app/node_modules/@babel/parser/lib/index.js:9319:98)
        at Object.parsePropertyName (/Users/weiran/repo/gitlab/rax-app/node_modules/@babel/parser/lib/index.js:2434:23)
        at Object.parseObjectMember (/Users/weiran/repo/gitlab/rax-app/node_modules/@babel/parser/lib/index.js:9220:10)
        at Object.parseObj (/Users/weiran/repo/gitlab/rax-app/node_modules/@babel/parser/lib/index.js:9154:25)
        at Object.parseExprAtom (/Users/weiran/repo/gitlab/rax-app/node_modules/@babel/parser/lib/index.js:8784:28)
        at Object.parseExprAtom (/Users/weiran/repo/gitlab/rax-app/node_modules/@babel/parser/lib/index.js:3601:20)
        at Object.parseExprSubscripts (/Users/weiran/repo/gitlab/rax-app/node_modules/@babel/parser/lib/index.js:8412:23)
        at Object.parseMaybeUnary (/Users/weiran/repo/gitlab/rax-app/node_modules/@babel/parser/lib/index.js:8392:21)
        at Object.parseExprOps (/Users/weiran/repo/gitlab/rax-app/node_modules/@babel/parser/lib/index.js:8267:23)
        at Object.parseMaybeConditional (/Users/weiran/repo/gitlab/rax-app/node_modules/@babel/parser/lib/index.js:8240:23)
        at Object.parseMaybeAssign (/Users/weiran/repo/gitlab/rax-app/node_modules/@babel/parser/lib/index.js:8187:21)
     @ ./src/pages/Home/index (multi ./node_modules/rax-plugin-ssr/src/ssr/loader.js?path=%2F&pageName=pages_Home_index&absoluteDocumentPath=%2FUsers%2Fweiran%2Frepo%2Fgitlab%2Frax-app%2Fsrc%2Fdocument%2Findex.jsx&absoluteShellPath=%2FUsers%2Fweiran%2Frepo%2Fgitlab%2Frax-app%2Fsrc%2Fshell%2Findex.jsx&absoluteAppPath=%2FUsers%2Fweiran%2Frepo%2Fgitlab%2Frax-app%2Fsrc%2Fapp.js&absolutePagePath=%2FUsers%2Fweiran%2Frepo%2Fgitlab%2Frax-app%2Fsrc%2Fpages%2FHome%2Findex&absoluteAppJSONPath=%2FUsers%2Fweiran%2Frepo%2Fgitlab%2Frax-app%2Fsrc%2Fapp.json&publicPath=%2F&isMultiPages=false&scripts%5B0%5D=web%2Fpages_Home_index.js&scripts%5B1%5D=web%2Findex.js!./src/pages/Home/index) pages_Home_index[0]
    
    ERROR in /Users/weiran/repo/gitlab/rax-app/tsconfig.json
    [tsl] ERROR
          TS6059: File '/Users/weiran/repo/gitlab/rax-app/node_modules/universal-app-runtime/lib/index.js' is not under 'rootDir' '/Users/weiran/repo/gitlab/rax-app/src'. 'rootDir' is expected to contain all source files.
    
    ERROR in /Users/weiran/repo/gitlab/rax-app/src/app.ts
    [tsl] ERROR in /Users/weiran/repo/gitlab/rax-app/src/app.ts(9,18)
          TS1005: '>' expected.
    
    ERROR in /Users/weiran/repo/gitlab/rax-app/src/app.ts
    [tsl] ERROR in /Users/weiran/repo/gitlab/rax-app/src/app.ts(9,30)
          TS1109: Expression expected.
    
    ERROR in /Users/weiran/repo/gitlab/rax-app/src/app.ts
    [tsl] ERROR in /Users/weiran/repo/gitlab/rax-app/src/app.ts(9,31)
          TS1109: Expression expected.
    
    ERROR in /Users/weiran/repo/gitlab/rax-app/src/app.ts
    [tsl] ERROR in /Users/weiran/repo/gitlab/rax-app/src/app.ts(1,1)
          TS6133: 'createElement' is declared but its value is never read.
    
    ERROR in /Users/weiran/repo/gitlab/rax-app/src/app.ts
    [tsl] ERROR in /Users/weiran/repo/gitlab/rax-app/src/app.ts(7,9)
          TS6133: 'Router' is declared but its value is never read.
    
    ERROR in /Users/weiran/repo/gitlab/rax-app/src/app.ts
    [tsl] ERROR in /Users/weiran/repo/gitlab/rax-app/src/app.ts(9,11)
          TS2749: 'Router' refers to a value, but is being used as a type here.
```

</detail>

repro: https://github.com/aladdin-add/rax-app

**Comment by Orange-C** [comment]
小程序jsx转换目前还不支持ts语法，app.js只能用js语法是因为app-shell-loader的处理没加上其他loader逻辑，我看到你有个PR处理这个问题，应该还是WIP？

**Comment by aladdin-add** [comment]
是的，那个PR修改了入口支持 app.ts，但是我发现改了之后还有问题：它还不认识css module

**Comment by aladdin-add** [comment]
如果不需要支持小程序的话呢，可以使用ts么？

**Comment by Orange-C** [comment]
其他文件可以使用，app.js比较特殊，还没支持，我们要处理一下

**Comment by Orange-C** [comment]
Closed due to expiration
